# Generated by Django 5.2.7 on 2025-11-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_category_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('technologie', 'Technologie'), ('developpement', 'Développement'), ('accessibilite', 'Accessibilité'), ('performance', 'Performance'), ('architecture', 'Architecture'), ('education', 'Éducation'), ('securite', 'Sécurité'), ('alpha_beta', 'Alpha/Beta'), ('gadget', 'Gadget'), ('design', 'Design'), ('autre', 'Autre')], max_length=100),
        ),
    ]
