# Generated by Django 5.2.7 on 2026-03-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_title'),
        ('blog', '0004_alter_post_category'),
    ]

    operations = [
    ]
