# Generated by Django 5.2.7 on 2025-11-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_created_at_contact_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
